# Generated by Django 5.2.8 on 2025-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
