# Generated by Django 5.2.8 on 2025-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_recording_summary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
