# Generated by Django 5.2.8 on 2025-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
