# Generated by Django 5.2.8 on 2025-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_recording_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
            preserve_default=False,
        ),
    ]
