# Generated by Django 5.2.8 on 2025-12-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_recording_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='conciseness_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filler_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='grammar_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='hedging_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='pacing_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='pacing_segments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recording',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
