# Generated by Django 5.2.8 on 2025-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='authorize_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
