# Generated by Django 5.2.8 on 2026-01-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_usersubscription_authorize_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
