# Generated by Django 5.2.8 on 2026-01-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_usersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='customer_payment_profile_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='customer_profile_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
