# Generated by Django 5.2.8 on 2026-01-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_usersubscription_customer_payment_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='customer_payment_profile_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='customer_profile_id',
        ),
    ]
