# Generated by Django 5.2.8 on 2026-01-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('dashboard', '0014_usersubscription_customer_payment_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='pending_subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription that will take effect at next billing cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_upgrades', to='adminpanel.subscription'),
        ),
    ]
