# Generated by Django 5.2.8 on 2026-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_usersubscription_pending_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='pending_authorize_subscription_id',
            field=models.CharField(blank=True, help_text='Authorize.Net subscription ID for pending downgrade', max_length=64, null=True),
        ),
    ]
